Fix: Start Apache & MySQL in CI before Cypress

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -44,4 +44,4 @@ jobs:
         run: npx cypress install || echo "Cypress already installed"
 
       - name: Run Cypress Tests
-        run: npm run test || (echo "ERROR: Cypress Tests Failed!" && exit 1)
+        run: npm run test || (echo "ERROR Cypress Tests Failed!" && exit 1)
